export const GET_LOGS = "GET_LOGS";
export const ADD_LOG = "ADD_LOG";
export const DELETE_LOG = "DELETE_LOG";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_LOG = "UPDATE_LOG";
export const CLEAR_LOGS = "CLEAR_LOGS";
export const SET_LOADING = "SET_LOADING";
export const LOGS_ERROR = "LOGS_ERROR";
export const SEARCH_LOGS = "SEARCH_LOGS";
export const GET_TECHS = "GET_TECHS";
export const ADD_TECH = "ADD_TECH";
export const DELETE_TECH = "DELETE_TECH";
export const TECHS_ERROR = "TECHS_ERROR";

export const GET_GENRES = "GET_GENERS";
export const GENRES_ERROR = "GENERS_ERROR";

export const GET_TOP_RATED = "GET_TOP_RATED";
export const TOP_RATED_ERROR = "TOP_RATED_ERROR";

export const GET_UPCOMING = "GET_UPCOMING";
export const UPCOMING_ERROR = "UPCOMING_ERROR";

export const GET_NOW_PLAYING = "GET_NOW_PLAYING";
export const NOW_PLAYING_ERROR = "NOW_PLAYING_ERROR";

export const GET_MOVIE_BY_GENRE = "GET_MOVIE_BY_GENRE";
export const MOVIE_BY_GENRE_ERROR = "MOVIE_BY_GENRE_ERROR";

export const GET_MOVIE = "GET_MOVIE";
export const MOVIE_ERROR = "MOVIE_ERROR";

export const GET_MOVIE_CAST = "GET_MOVIE_CAST";
export const MOVIE_CAST_ERROR = "MOVIE_CAST_ERROR";

export const GET_MOVIE_SEARCH = "GET_MOVIE_SEARCH";
export const MOVIE_SEARCH_ERROR = "MOVIE_SEARCH_ERROR";

export const GET_MOVIE_VIDEOS = "GET_MOVIE_VIDEOS";
export const MOVIE_VIDEOS_ERROR = "MOVIE_VIDEOS_ERROR";

export const GET_PERSON = "GET_PERSON";
export const PERSON_ERROR = "PERSON_ERROR";

export const GET_RECOMMENDED_MOVIES = "GET_RECOMMENDED_MOVIES";
export const RECOMMENDED_MOVIES_ERROR = "RECOMMENDED_MOVIES_ERROR";

export const GET_PERSON_MOVIES = "GET_PERSON_MOVIES";
export const PERSON_MOVIES_ERROR = "PERSON_MOVIES_ERROR";