export const GET_POPULARS = "GET_POPULARS";
export const GET_POPULARS_ERROR = "GET_POPULARS_ERROR";
export const GET_POPULARS_CLEAR = "GET_POPULARS_CLEAR";

export const SEARCH_LOGS = "SEARCH_LOGS";
export const GET_TECHS = "GET_TECHS";
export const ADD_TECH = "ADD_TECH";
export const DELETE_TECH = "DELETE_TECH";
export const TECHS_ERROR = "TECHS_ERROR";

export const GET_GENRES = "GET_GENERS";
export const GET_GENRES_CLEAR = "GET_GENERS_CLEAR";
export const GENRES_ERROR = "GENERS_ERROR";

export const GET_TOP_RATED = "GET_TOP_RATED";
export const GET_TOP_RATED_CLEAR = "GET_TOP_RATED_CLEAR";
export const TOP_RATED_ERROR = "TOP_RATED_ERROR";

export const GET_UPCOMING = "GET_UPCOMING";
export const GET_UPCOMING_CLEAR = "GET_UPCOMING_CLEAR";
export const UPCOMING_ERROR = "UPCOMING_ERROR";

export const GET_NOW_PLAYING = "GET_NOW_PLAYING";
export const GET_NOW_PLAYING_CLEAR = "GET_NOW_PLAYING_CLEAR";
export const NOW_PLAYING_ERROR = "NOW_PLAYING_ERROR";

export const GET_MOVIE_BY_GENRE = "GET_MOVIE_BY_GENRE";
export const MOVIE_BY_GENRE_CLEAR = "MOVIE_BY_GENRE_CLEAR";
export const MOVIE_BY_GENRE_ERROR = "MOVIE_BY_GENRE_ERROR";

export const GET_MOVIE = "GET_MOVIE";
export const GET_MOVIE_CLEAR = "GET_MOVIE_CLEAR";
export const MOVIE_ERROR = "MOVIE_ERROR";

export const GET_MOVIE_CAST = "GET_MOVIE_CAST";
export const CLEAR_MOVIE_CAST = "CLEAR_MOVIE_CAST";
export const MOVIE_CAST_ERROR = "MOVIE_CAST_ERROR";

export const GET_MOVIE_SEARCH = "GET_MOVIE_SEARCH";
export const MOVIE_SEARCH_ERROR = "MOVIE_SEARCH_ERROR";

export const GET_MOVIE_VIDEOS = "GET_MOVIE_VIDEOS";
export const CLEAR_MOVIE_VIDEOS = "CLEAR_MOVIE_VIDEOS";
export const MOVIE_VIDEOS_ERROR = "MOVIE_VIDEOS_ERROR";

export const GET_PERSON = "GET_PERSON";
export const GET_PERSON_CLEAR = "GET_PERSON_CLEAR";
export const PERSON_ERROR = "PERSON_ERROR";

export const GET_RECOMMENDED_MOVIES = "GET_RECOMMENDED_MOVIES";
export const CLEAR_RECOMMENDED_MOVIES = "CLEAR_RECOMMENDED_MOVIES";
export const RECOMMENDED_MOVIES_ERROR = "RECOMMENDED_MOVIES_ERROR";

export const GET_PERSON_MOVIES = "GET_PERSON_MOVIES";
export const CLEAR_PERSON_MOVIES = "CLEAR_PERSON_MOVIES";
export const PERSON_MOVIES_ERROR = "PERSON_MOVIES_ERROR";